### ISSUE TITLE
Some updates?

### ISSUE THREAD

**Issue by zhaozhongch** [ethz-asl/scenenet_to_rosbag#9]
Thanks for your work.
But I met some problems to download the file.
When I run
```
wget http://www.doc.ic.ac.uk/~ahanda/train_protobufs.tar.gz train_protobufs.tar.gz
``` 
The error is 
```
URL transformed to HTTPS due to an HSTS policy
--2020-06-13 11:39:00--  https://www.doc.ic.ac.uk/~ahanda/train_protobufs.tar.gz
Resolving www.doc.ic.ac.uk (www.doc.ic.ac.uk)... 146.169.13.6
Connecting to www.doc.ic.ac.uk (www.doc.ic.ac.uk)|146.169.13.6|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-06-13 11:39:02 ERROR 403: Forbidden.

--2020-06-13 11:39:02--  http://train_protobufs.tar.gz/
Resolving train_protobufs.tar.gz (train_protobufs.tar.gz)... failed: Name or service not known.
wget: unable to resolve host address ‘train_protobufs.tar.gz’
```
Then I go to the [scenenet website](https://robotvault.bitbucket.io/scenenet-rgbd.html) to download `train_protobufs.tar.gz` manually then I tried
```
tar -xvzf train_protobufs.tar.gz --strip=1
```
Then errors again
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

According to the error, the file is not in gzip format. Then I use 
```
tar xvf train_protobufs.tar.gz --strip=1
``` 
to uncompress it but here I am not sure if can yield the same thing as your original command `tar xvzf ...` because I don't the the meaning of `--strip==1`

**Comment by margaritaG** [comment]
@zhaozhongch Thanks for pointing out the broken links, I have updated the instructions in the README. 
Everything should be working as expected now, so just give it one more try.
